<a href="https://colab.research.google.com/github/Tharunvikas55/ML/blob/main/Neural_Network_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def derivative_sigmoid(x):
  return x*(1-x)

In [12]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [13]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [14]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr


In [15]:
output

array([[0.9483918 ],
       [0.07358864],
       [0.95682984]])

Iris Dataset

In [ ]:
# Import necessary libraries
import numpy as np
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# Preprocess the data
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])  # One-hot encode the target variable
    ],
    remainder='passthrough'
)

y = np.array(ct.fit_transform(y), dtype=np.float32)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_dim=4, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=5)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')


In [17]:
import numpy as np
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# Preprocess the data
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])  # One-hot encode the target variable
    ],
    remainder='passthrough'
)

y = np.array(ct.fit_transform(y), dtype=np.float32)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert data to TensorFlow tensors
X_train_tf = tf.constant(X_train, dtype=tf.float32)
y_train_tf = tf.constant(y_train, dtype=tf.float32)
X_test_tf = tf.constant(X_test, dtype=tf.float32)
y_test_tf = tf.constant(y_test, dtype=tf.float32)

# Define the neural network architecture
class NeuralNetwork:
    def __init__(self):
        self.weights = tf.Variable(tf.random.normal([4, 3], stddev=0.1), trainable=True)
        self.biases = tf.Variable(tf.zeros([3]), trainable=True)

    def forward(self, inputs):
        return tf.nn.softmax(tf.matmul(inputs, self.weights) + self.biases)

# Training parameters
learning_rate = 0.01
epochs = 1000

# Initialize the model
model = NeuralNetwork()

# Training loop
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        predictions = model.forward(X_train_tf)
        loss = tf.reduce_mean(tf.keras.losses.categorical_crossentropy(y_train_tf, predictions))

    # Compute gradients and update weights
    gradients = tape.gradient(loss, [model.weights, model.biases])
    model.weights.assign_sub(learning_rate * gradients[0])
    model.biases.assign_sub(learning_rate * gradients[1])

    # Print training progress
    if (epoch + 1) % 100 == 0:
        print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss.numpy():.4f}')

# Evaluate the model on the test set
test_predictions = model.forward(X_test_tf)
test_loss = tf.reduce_mean(tf.keras.losses.categorical_crossentropy(y_test_tf, test_predictions))
accuracy = tf.reduce_mean(tf.keras.metrics.categorical_accuracy(y_test_tf, test_predictions))

print(f'Test Loss: {test_loss.numpy():.4f}, Test Accuracy: {accuracy.numpy():.4f}')


Epoch 100/1000, Loss: 0.6154
Epoch 200/1000, Loss: 0.5149
Epoch 300/1000, Loss: 0.4639
Epoch 400/1000, Loss: 0.4311
Epoch 500/1000, Loss: 0.4073
Epoch 600/1000, Loss: 0.3886
Epoch 700/1000, Loss: 0.3733
Epoch 800/1000, Loss: 0.3602
Epoch 900/1000, Loss: 0.3487
Epoch 1000/1000, Loss: 0.3384
Test Loss: 0.2839, Test Accuracy: 0.9667


In [18]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load Breast Cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target.reshape(-1, 1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert data to TensorFlow tensors
X_train_tf = tf.constant(X_train, dtype=tf.float32)
y_train_tf = tf.constant(y_train, dtype=tf.float32)
X_test_tf = tf.constant(X_test, dtype=tf.float32)
y_test_tf = tf.constant(y_test, dtype=tf.float32)

# Define the neural network architecture
class NeuralNetwork:
    def __init__(self):
        self.weights = tf.Variable(tf.random.normal([X_train.shape[1], 1], stddev=0.1), trainable=True)
        self.biases = tf.Variable(tf.zeros([1]), trainable=True)

    def forward(self, inputs):
        return tf.nn.sigmoid(tf.matmul(inputs, self.weights) + self.biases)

# Training parameters
learning_rate = 0.01
epochs = 1000

# Initialize the model
model = NeuralNetwork()

# Training loop
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        predictions = model.forward(X_train_tf)
        loss = tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_train_tf, predictions))

    # Compute gradients and update weights
    gradients = tape.gradient(loss, [model.weights, model.biases])
    model.weights.assign_sub(learning_rate * gradients[0])
    model.biases.assign_sub(learning_rate * gradients[1])

    # Print training progress
    if (epoch + 1) % 100 == 0:
        print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss.numpy():.4f}')

# Evaluate the model on the test set
test_predictions = model.forward(X_test_tf)
test_predictions_binary = tf.where(test_predictions >= 0.5, 1.0, 0.0)
accuracy = accuracy_score(y_test_tf, test_predictions_binary)

print(f'Test Accuracy: {accuracy:.4f}')


Epoch 100/1000, Loss: 0.2664
Epoch 200/1000, Loss: 0.1983
Epoch 300/1000, Loss: 0.1681
Epoch 400/1000, Loss: 0.1502
Epoch 500/1000, Loss: 0.1381
Epoch 600/1000, Loss: 0.1292
Epoch 700/1000, Loss: 0.1224
Epoch 800/1000, Loss: 0.1169
Epoch 900/1000, Loss: 0.1124
Epoch 1000/1000, Loss: 0.1086
Test Accuracy: 0.9649
