<a href="https://colab.research.google.com/github/Tharunvikas55/ML/blob/main/Neural_Network_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def derivative_sigmoid(x):
  return x*(1-x)

In [12]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [13]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [14]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr


In [15]:
output

array([[0.9483918 ],
       [0.07358864],
       [0.95682984]])